version: '3'
services:
  postgres:
    image: postgres:17.2-alpine3.20
    container_name: postgres-database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    command:
      - "postgres"
      - "-c"
      - "shared_preload_libraries=pgoutput"
      - "-c"
      - "wal_level=logical"
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - ./test_data_postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres_data:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"